### PR TITLE
First bunch of Generic keywords

### PR DESCRIPTION
**Pull request by isaonu**
Keywords for adb commands, SerialPorts and File added. Custom Library added for lists.

### CODE REVIEW

**Review by danielOmnitracs — APPROVED** [review]

**Review by danielOmnitracs — APPROVED** [review]

**Comment by isaonu** [comment]
> **for handlelist.py** ==> these methods can be really useful when it is necessary. It gave me the idea to check my BrowserUtils classes in java :) And it would be great if you can show a little demo for "delete_elements_from_list" method.
 _Ill show it in the meeting._

> **File.resource** => line 15 "get matches" keyword comes from Collections Library? Cuz it is hard to find in VS the source of the keywords.
_Yes, it comes from Collections Library, I added the Library._

> => line 58 "Create Command Configuration File with a Command in Local Folder" is it possible if this keyword returns "the path of the file" that we newly created.
_We can discuss this in the meeting._

> **adb.resource** = > line 92 "The Device is Rebooted" in this keyword can we make the last "sleep 30s" optional? For example the default sleep time can be defined as "timeout=30" in arguments, when we call this keyword we can implement the wait time, what you think? Or we can
> talk this matter on thursday/Friday.
_Yes, good suggestion, I agree with you, I added it._

> = > line 108 "Get Process Id of an App from Device" this keyword looks really useful in order to check the applications running status.
_Thanks!_

> => line 134 what about re-naming keyword "Start App with Activity on Device" or something similar.
_Yes, it sounds better as you suggest, I changed it._

> Currently I haven't started testing applications, therefore I just try to understand the main functionality you build for adb.resource file. On the other side I will implement the keywords in File.resource into my test cases, lets see what else things we can talk in terms of re-usability of the keywords.
> Thank you for your shares.
_Your welcome!_ :)

**Comment by isaonu** [comment]
> File.resource => line 50 We are using "Show File Content from Device in Shell" keyword, I think for that reason we have to add "Resource adb.resource" into the Settings section of the file.

_Yes you are right, I added it._

**Comment by isaonu** [comment]
> line 20 => just an optional idea: for the keyword "String Appears in X min Y Times in Log", can we change the min into seconds?
> line 64 => Can we update the name of the keyword "Word is in Log File More Than N Times"?
> 
> I remember you had presented to me this class also when we first met. But now when I checked it detailly I realized that I could have used many of these keywords in VDS layer folders that I had shared with you yesterday. So in general, really useful keywords but moreover really dynamic and re-usable/scalable in order to implement in our codes. Lets see before our meeting if I can implement these keywords into the classes that I shared.

_About this two, we can discuss them in the meeting_
_Related to the name, if would be nice if you have some in mind for the meeting_

**Review by danielOmnitracs — APPROVED** [review]

**Comment by isaonu** [comment]
> Among the "pushes" I did, there is a python module in CustomLibraries/logParser.py, when you have time can you please check it. It is a simple function to take a slice from log file (I also tried to give some examples inside the file). Of course we can talk it in our meeting and maybe we can add that function as a keyword inside the File.resource class. (including changing the name of the function)

_Ive checked it, it looks very useful, and it gave me another idea!. Lets talk about this in the meeting._

**Review by danielOmnitracs — APPROVED** [review]

**Comment by isaonu** [comment]
> Here can we add a message like:
> Should Be True ${result} msg=In ${log_name} logs could NOT encounter '${specified_string}' keyword in ${time_to_wait} mins!
> Because the method that we are calling from TitanLibrary is printing the details but in the reports of RF we can not see it unless we know where to look.
> I tried to add a screenshot to explain it, i hope i was clear. :)
> report

Ok I agree with you, it seems very usefult. What do you think if we left that for another branch? I think we have too many changes here, maybe we can close this and add those and maybe future improvement in a new branch?

**Pull request merged**
