### PR TITLE
Some keywords for vsim

### PR DESCRIPTION
**Pull request by VatanHorasan06**
Need some review :)

### CODE REVIEW

**Comment by isaonu** [comment]
I only have two comments,

In Resources/SharedTools/Files.resource 
Will it be possible to write it as title case, this part
logParser.get text surrounded by string 
so it will be logParser.Get Text Surrounded by String
?

Data/DiagnosticsApplication.resource
I thinks this can be moved to Resource folder since this is not actual data but a resource, for example something like Resources/DiagnosticsApplication folder, what do you think?

In general it looks very good and reusable!

**Comment by VatanHorasan06** [comment]
For the first comment:
I got your point, sorry for the repeating error, will fix it now.

For your second comment:
This class, in my own project, is inside Resource folder. As far i understood we had talked about that we have to put the PO classes inside Data folder. That was the reason i put over there. Or maybe i was lost in translation.
No worries i will change the location.
Thanks for your comments and your time.

**Comment by isaonu** [comment]
Thanks for sharing! :)

**Review by isaonu — APPROVED** [review]
Im seems ready!

**Pull request merged**
